<?php

namespace Database\Seeders;

use App\Models\MaintenanceRequest;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class MaintenanceRequestSeeder extends Seeder
{
    public function run(): void
    {
        $requests = [
            [
                'venue_id' => 1,
                'equipment_id' => null,
                'title' => 'Air Conditioning Malfunction',
                'description' => 'AC unit in Grand Auditorium is not cooling properly. Temperature remains at 78°F despite being set to 68°F.',
                'priority' => 'high',
                'status' => 'in_progress',
                'scheduled_date' => Carbon::now()->addDays(1)->setTime(9, 0),
                'notes' => 'HVAC technician scheduled for tomorrow morning.',
                'assigned_to' => 2,
                'created_at' => Carbon::now()->subDays(2),
            ],
            [
                'venue_id' => 4,
                'equipment_id' => null,
                'title' => 'Replace Fluorescent Lights',
                'description' => 'Several fluorescent lights in Computer Lab 1 are flickering and need replacement.',
                'priority' => 'medium',
                'status' => 'scheduled',
                'scheduled_date' => Carbon::now()->addDays(5)->setTime(14, 0),
                'notes' => 'Replacement bulbs ordered. Maintenance scheduled for weekend.',
                'assigned_to' => null,
                'created_at' => Carbon::now()->subDays(3),
            ],
            [
                'venue_id' => 2,
                'equipment_id' => 3,
                'title' => 'Projector Bulb Replacement',
                'description' => 'Projector bulb in Conference Room A is dimming. Image quality degraded.',
                'priority' => 'high',
                'status' => 'open',
                'scheduled_date' => null,
                'notes' => null,
                'assigned_to' => null,
                'created_at' => Carbon::now()->subDays(1),
            ],
            [
                'venue_id' => 5,
                'equipment_id' => null,
                'title' => 'Ventilation System Inspection',
                'description' => 'Annual inspection of ventilation system in Engineering Workshop as per safety regulations.',
                'priority' => 'medium',
                'status' => 'scheduled',
                'scheduled_date' => Carbon::now()->addDays(10)->setTime(10, 0),
                'notes' => 'Annual safety inspection. Must be completed before next semester.',
                'assigned_to' => 2,
                'created_at' => Carbon::now()->subDays(7),
            ],
            [
                'venue_id' => 8,
                'equipment_id' => null,
                'title' => 'Repair Outdoor Tables',
                'description' => 'Three tables at Outdoor Pavilion have wobbly legs and need reinforcement.',
                'priority' => 'low',
                'status' => 'open',
                'scheduled_date' => null,
                'notes' => null,
                'assigned_to' => null,
                'created_at' => Carbon::now()->subHours(48),
            ],
            [
                'venue_id' => 9,
                'equipment_id' => 22,
                'title' => 'Green Screen Tear Repair',
                'description' => 'Small tear in green screen fabric needs patching to maintain chroma key quality.',
                'priority' => 'medium',
                'status' => 'in_progress',
                'scheduled_date' => Carbon::now()->setTime(15, 0),
                'notes' => 'Repair kit ordered. Will be fixed today afternoon.',
                'assigned_to' => 2,
                'created_at' => Carbon::now()->subDays(1),
            ],
            [
                'venue_id' => 7,
                'equipment_id' => null,
                'title' => 'Clean Projection Screen',
                'description' => 'Projection screen has dust and marks affecting image quality.',
                'priority' => 'low',
                'status' => 'open',
                'scheduled_date' => null,
                'notes' => null,
                'assigned_to' => null,
                'created_at' => Carbon::now()->subHours(24)  ,
            ],
            [
                'venue_id' => 10,
                'equipment_id' => 18,
                'title' => 'Medical Mannequin Battery Replacement',
                'description' => 'Battery in medical mannequin #3 needs replacement. Currently not holding charge.',
                'priority' => 'medium',
                'status' => 'scheduled',
                'scheduled_date' => Carbon::now()->addDays(3)->setTime(11, 0),
                'notes' => 'Replacement battery on order. Expected delivery in 2 days.',
                'assigned_to' => 2,
                'created_at' => Carbon::now()->subDays(4),
            ],
            [
                'venue_id' => 12,
                'equipment_id' => null,
                'title' => 'Gallery Lighting Adjustment',
                'description' => 'Gallery track lighting needs adjustment and focusing for upcoming exhibition.',
                'priority' => 'medium',
                'status' => 'scheduled',
                'scheduled_date' => Carbon::now()->addDays(2)->setTime(9, 0),
                'notes' => 'Scheduled before next art exhibition setup.',
                'assigned_to' => null,
                'created_at' => Carbon::now()->subDays(5),
            ],
            [
                'venue_id' => 3,
                'equipment_id' => null,
                'title' => 'Deep Clean After Event',
                'description' => 'Student Activity Hall needs thorough cleaning after large weekend event.',
                'priority' => 'urgent',
                'status' => 'completed',
                'scheduled_date' => Carbon::now()->subDays(1)->setTime(7, 0),
                'notes' => 'Cleaning completed. Venue ready for use.',
                'assigned_to' => 2,
                'created_at' => Carbon::now()->subDays(2),
            ],
            [
                'venue_id' => 11,
                'equipment_id' => null,
                'title' => 'Coffee Machine Servicing',
                'description' => 'Coffee machine in Business Innovation Hub needs descaling and general maintenance.',
                'priority' => 'low',
                'status' => 'open',
                'scheduled_date' => null,
                'notes' => null,
                'assigned_to' => null,
                'created_at' => Carbon::now()->subHours(18),
            ],
            [
                'venue_id' => 13,
                'equipment_id' => null,
                'title' => 'Whiteboard Resurfacing',
                'description' => 'Whiteboard in Sports Complex Meeting Room has permanent marker stains and needs resurfacing.',
                'priority' => 'low',
                'status' => 'open',
                'scheduled_date' => null,
                'notes' => null,
                'assigned_to' => null,
                'created_at' => Carbon::now()->subHours(36),
            ],
            [
                'venue_id' => 6,
                'equipment_id' => null,
                'title' => 'WiFi Signal Improvement',
                'description' => 'WiFi signal in Seminar Room B is weak in certain areas. May need additional access point.',
                'priority' => 'medium',
                'status' => 'open',
                'scheduled_date' => null,
                'notes' => 'IT department to assess signal strength and recommend solution.',
                'assigned_to' => null,
                'created_at' => Carbon::now()->subDays(6),
            ],
            [
                'venue_id' => 14,
                'equipment_id' => null,
                'title' => 'Renovation Progress Update',
                'description' => 'Conference Room C renovation project is 60% complete. Painting and flooring in progress.',
                'priority' => 'low',
                'status' => 'in_progress',
                'scheduled_date' => Carbon::now()->addDays(30)->setTime(8, 0),
                'notes' => 'Renovation on schedule. Expected completion by end of month.',
                'assigned_to' => 2,
                'created_at' => Carbon::now()->subDays(20),
            ],
            [
                'venue_id' => 1,
                'equipment_id' => 1,
                'title' => 'Wireless Microphone Frequency Check',
                'description' => 'Perform routine frequency check and testing on all wireless microphones.',
                'priority' => 'low',
                'status' => 'completed',
                'scheduled_date' => Carbon::now()->subDays(7)->setTime(13, 0),
                'notes' => 'All systems tested and working properly. Batteries replaced.',
                'assigned_to' => 2,
                'created_at' => Carbon::now()->subDays(10),
            ],
        ];

        foreach ($requests as $request) {
            MaintenanceRequest::create($request);
        }
    }
}
