// Mock data for development

import type { User, Venue, Equipment, Booking, MaintenanceRequest, ScheduledMaintenance, Department, AuditLog } from "./types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "edgar.garan@umindanao.edu.ph",
    name: "Edgar Allain Sobremonte Garan",
    role: "organizer",
    department: "Bachelor of Science in Information Technology",
    college: "College of Computer Studies",
    position: "Event Organizer",
    isOnboarded: true,
    avatar: "EA",
  },
  {
    id: "admin-1",
    email: "admin@umindanao.edu.ph",
    name: "Maria Santos",
    role: "admin",
    department: "Facilities Management",
    college: "University Administration",
    position: "Facility Manager",
    isOnboarded: true,
    avatar: "MS",
  },
  {
    id: "user-2",
    email: "newuser@umindanao.edu.ph",
    name: "John Doe",
    role: "organizer",
    isOnboarded: false,
    avatar: "JD",
  },
]

export const mockVenues: Venue[] = [
  {
    id: "venue-1",
    name: "Matina Collaboration Room 101",
    capacity: 50,
    location: "Matina Campus, Building A",
    image: "/modern-collaboration-room-with-tables-and-chairs.jpg",
    description: "Modern collaboration space with multimedia equipment",
    status: "available",
  },
  {
    id: "venue-2",
    name: "Matina Collaboration Room 102",
    capacity: 75,
    location: "Matina Campus, Building A",
    image: "/large-conference-room-with-presentation-setup.jpg",
    description: "Large conference room with advanced AV setup",
    status: "available",
  },
  {
    id: "venue-3",
    name: "Matina Collaboration Room 103",
    capacity: 100,
    location: "Matina Campus, Building B",
    image: "/auditorium-style-event-space.jpg",
    description: "Auditorium-style space for large events",
    status: "available",
  },
  {
    id: "venue-4",
    name: "Davao Campus Event Hall",
    capacity: 200,
    location: "Davao Campus",
    image: "/large-event-hall-with-stage.jpg",
    description: "Large event hall suitable for major university events",
    status: "available",
  },
]

export const mockEquipment: Equipment[] = [
  {
    id: "eq-1",
    name: "Projector",
    category: "Audio Visual",
    quantity: 10,
    available: 8,
    venueId: "venue-1",
    description: "HD Projector with HDMI and VGA inputs",
  },
  {
    id: "eq-2",
    name: "Sound System",
    category: "Audio Visual",
    quantity: 5,
    available: 4,
    venueId: "venue-2",
    description: "Professional sound system with microphones",
  },
  {
    id: "eq-3",
    name: "Whiteboard",
    category: "Office Supplies",
    quantity: 15,
    available: 12,
    venueId: "venue-1",
    description: "Large interactive whiteboard",
  },
  {
    id: "eq-4",
    name: "Chairs",
    category: "Furniture",
    quantity: 500,
    available: 450,
    venueId: "venue-3",
    description: "Stackable event chairs",
  },
]

export const mockBookings: Booking[] = [
  {
    id: "booking-1",
    organizerId: "user-1",
    venueId: "venue-1",
    eventTitle: "IT Department Seminar",
    eventDescription: "Annual IT department seminar on emerging technologies",
    startDate: "2025-11-15",
    endDate: "2025-11-15",
    startTime: "09:00",
    endTime: "12:00",
    expectedAttendees: 45,
    equipment: [{ equipmentId: "eq-1", quantity: 1 }],
    documents: [],
    status: "approved",
    createdAt: "2025-10-20T10:00:00Z",
    updatedAt: "2025-10-21T14:30:00Z",
  },
  {
    id: "booking-2",
    organizerId: "user-1",
    venueId: "venue-2",
    eventTitle: "Student Workshop",
    eventDescription: "Workshop on web development and modern frameworks",
    startDate: "2025-11-20",
    endDate: "2025-11-20",
    startTime: "14:00",
    endTime: "17:00",
    expectedAttendees: 60,
    equipment: [
      { equipmentId: "eq-1", quantity: 1 },
      { equipmentId: "eq-2", quantity: 1 },
    ],
    documents: [],
    status: "pending",
    createdAt: "2025-10-25T11:00:00Z",
    updatedAt: "2025-10-25T11:00:00Z",
  },
]

export const mockMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: "maint-1",
    venueId: "venue-1",
    title: "Air Conditioning Not Working",
    description: "The AC unit in the room is not cooling properly",
    priority: "high",
    status: "pending",
    reportedBy: "user-1",
    createdAt: "2025-11-10T08:00:00Z",
  },
  {
    id: "maint-2",
    venueId: "venue-2",
    title: "Projector Bulb Replacement",
    description: "Projector bulb is dim and needs replacement",
    priority: "medium",
    status: "in-progress",
    reportedBy: "admin-1",
    assignedTo: "Maintenance Team A",
    createdAt: "2025-11-08T14:00:00Z",
  },
  {
    id: "maint-3",
    venueId: "venue-3",
    title: "Broken Chairs",
    description: "Three chairs have broken legs and need repair",
    priority: "low",
    status: "completed",
    reportedBy: "user-1",
    assignedTo: "Maintenance Team B",
    createdAt: "2025-11-05T10:00:00Z",
    completedAt: "2025-11-07T16:00:00Z",
  },
]

export const mockScheduledMaintenance: ScheduledMaintenance[] = [
  {
    id: "sched-1",
    venueId: "venue-1",
    title: "Monthly Deep Cleaning",
    description: "Comprehensive cleaning of the entire venue",
    scheduledDate: "2025-11-25",
    scheduledTime: "06:00",
    estimatedDuration: "4 hours",
    status: "scheduled",
    assignedTo: "Cleaning Services",
    createdAt: "2025-11-01T09:00:00Z",
  },
  {
    id: "sched-2",
    venueId: "venue-2",
    title: "HVAC System Inspection",
    description: "Quarterly inspection and maintenance of HVAC system",
    scheduledDate: "2025-11-28",
    scheduledTime: "08:00",
    estimatedDuration: "3 hours",
    status: "scheduled",
    assignedTo: "HVAC Technicians",
    createdAt: "2025-11-01T09:00:00Z",
  },
]

export const mockDepartments: Department[] = [
  {
    id: "dept-1",
    name: "Bachelor of Science in Information Technology",
    college: "College of Computer Studies",
    headOfDepartment: "Dr. Juan Dela Cruz",
    email: "bsit@umindanao.edu.ph",
    totalMembers: 45,
    activeEvents: 8,
  },
  {
    id: "dept-2",
    name: "Bachelor of Science in Computer Science",
    college: "College of Computer Studies",
    headOfDepartment: "Dr. Maria Garcia",
    email: "bscs@umindanao.edu.ph",
    totalMembers: 38,
    activeEvents: 5,
  },
  {
    id: "dept-3",
    name: "Bachelor of Science in Business Administration",
    college: "College of Business Administration",
    headOfDepartment: "Dr. Roberto Santos",
    email: "bsba@umindanao.edu.ph",
    totalMembers: 52,
    activeEvents: 12,
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    userId: "admin-1",
    userName: "Maria Santos",
    action: "Approved Booking",
    target: "booking-1",
    details: "Approved IT Department Seminar booking for Matina Collaboration Room 101",
    timestamp: "2025-11-10T14:30:00Z",
    ipAddress: "192.168.1.100",
  },
  {
    id: "audit-2",
    userId: "user-1",
    userName: "Edgar Allain Sobremonte Garan",
    action: "Created Booking",
    target: "booking-2",
    details: "Created new booking request for Student Workshop",
    timestamp: "2025-11-10T11:00:00Z",
    ipAddress: "192.168.1.150",
  },
  {
    id: "audit-3",
    userId: "admin-1",
    userName: "Maria Santos",
    action: "Updated Venue",
    target: "venue-1",
    details: "Changed venue status from maintenance to available",
    timestamp: "2025-11-09T10:15:00Z",
    ipAddress: "192.168.1.100",
  },
]
